pod 'ObjCMongoDB', '~> 0.11.0'
pod 'CocoaLumberjack', '~> 1.9'
pod 'AFJSONRPCClient'
pod 'GZIP', '~> 1.0.3'
pod 'SSZipArchive', '~> 0.3.2'
pod 'MBProgressHUD', '~> 0.9'
pod 'FMDB', '~> 2.4'
pod 'JSBadgeView', '~> 1.3.2'
pod 'MWPhotoBrowser', '~> 1.4.1'
pod 'pop', '~> 1.0'
pod 'SECoreTextView', '~> 0.8.4'
pod 'AppRTC', '~> 1.0.1'
pod 'Masonry', '~> 0.6.1'
pod 'JSONModel', '~> 1.1.0'
pod 'DateTools', '~> 1.5.0'
pod 'MMPlaceHolder', '~> 1.8'
pod 'SlackTextViewController', '~> 1.5.2'
