pod 'ObjCMongoDB', '~> 0.11.0'
pod 'CocoaLumberjack', '~> 1.9'
pod 'AFJSONRPCClient'
pod 'GZIP', '~> 1.0.3'
pod 'SSZipArchive', '~> 0.3.2'
pod 'MBProgressHUD', '~> 0.9'
pod 'FMDB', '~> 2.4'
pod 'JSQMessagesViewController', '~> 6.1.1'
pod 'JSBadgeView', '~> 1.3.2'
